version: '3'
services:
  vue-app:
    build:
      context: ./vue-todo-app
      dockerfile: Dockerfile.dev
    container_name: vue-todo-app-dev
    volumes:
      - ./vue-todo-app:/app
      - ./vue-todo-app/node_modules:/app/node_modules
      - ./vue-todo-app/public:/app/public
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: npm run serve
  api:
    build:
      context: api-fastapi
      dockerfile: Dockerfile.dev
    container_name: vue-todo-api-dev
    volumes:
      - ./api-fastapi:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
