version: '3.8'

services:
  vue-app:
    build:
      context: vue-todo-app
      dockerfile: Dockerfile.dev
    container_name: vue-todo-app-dev
    volumes:
      - ./vue-todo-app:/app
      - ./vue-todo-app/public:/app/public
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: npm run serve


