FROM python:3.11

WORKDIR /app

COPY . /app

# COPY requirements.txt /app/
# RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

# Define environment variable
# ENV NAME World

# Run app.py when the container launches
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
# CMD [ "sleep", "1d" ]