# Use an official Node runtime as the base image
FROM node:20

# Set the working directory in the container
WORKDIR /app

RUN npm install -g @vue/cli
RUN npm install -g @vue/cli-service

# Copy package.json and package-lock.json to the working directory
COPY package*.json .

# Install project dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port the app runs on
EXPOSE 8080

# Command to run the application
CMD ["npm", "run", "serve"]
